# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: dbcontainer
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  djangoapp:
    image: djangoapp
    container_name: djangoapp
    #user: myuser
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      POSTGRES_PASSWORD: example
    depends_on:
      - db
